// Code generated by "stringer -type=Type"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Operator-0]
	_ = x[OpenCurve-1]
	_ = x[CloseCurve-2]
	_ = x[OpenSquare-3]
	_ = x[CloseSquare-4]
	_ = x[OpenCurly-5]
	_ = x[CloseCurly-6]
	_ = x[Equals-7]
	_ = x[Number-8]
	_ = x[Text-9]
	_ = x[Bool-10]
	_ = x[Alpha-11]
}

const _Type_name = "OperatorOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyEqualsNumberTextBoolAlpha"

var _Type_index = [...]uint8{0, 8, 17, 27, 37, 48, 57, 67, 73, 79, 83, 87, 92}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
