// Code generated by "stringer -type=Type"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Dash-1]
	_ = x[Times-2]
	_ = x[Slash-3]
	_ = x[Power-4]
	_ = x[LogicOr-5]
	_ = x[LogicAnd-6]
	_ = x[BitwiseOr-7]
	_ = x[BitwiseAnd-8]
	_ = x[BitwiseXor-9]
	_ = x[Equals-10]
	_ = x[NotEquals-11]
	_ = x[LessThan-12]
	_ = x[LessThanEqual-13]
	_ = x[GreatThan-14]
	_ = x[GreaterThanEqual-15]
	_ = x[TextEquals-16]
	_ = x[TextNotEquals-17]
	_ = x[TextLessThan-18]
	_ = x[TextGreaterThan-19]
	_ = x[OpenCurve-20]
	_ = x[CloseCurve-21]
	_ = x[OpenSquare-22]
	_ = x[CloseSquare-23]
	_ = x[OpenCurly-24]
	_ = x[CloseCurly-25]
	_ = x[Assign-26]
	_ = x[Dot-27]
	_ = x[Comma-28]
	_ = x[Question-29]
	_ = x[Not-30]
	_ = x[Colon-31]
	_ = x[DoubleColon-32]
	_ = x[RightArrow-33]
	_ = x[Underscore-34]
	_ = x[True-35]
	_ = x[False-36]
	_ = x[Text-37]
	_ = x[Number-38]
	_ = x[Name-39]
	_ = x[Color-40]
	_ = x[If-41]
	_ = x[Elif-42]
	_ = x[Else-43]
	_ = x[For-44]
	_ = x[To-45]
	_ = x[By-46]
	_ = x[Each-47]
	_ = x[In-48]
	_ = x[While-49]
	_ = x[Do-50]
	_ = x[Break-51]
	_ = x[WalkAll-52]
	_ = x[Global-53]
	_ = x[Local-54]
	_ = x[This-55]
	_ = x[Func-56]
}

const _Type_name = "PlusDashTimesSlashPowerLogicOrLogicAndBitwiseOrBitwiseAndBitwiseXorEqualsNotEqualsLessThanLessThanEqualGreatThanGreaterThanEqualTextEqualsTextNotEqualsTextLessThanTextGreaterThanOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyAssignDotCommaQuestionNotColonDoubleColonRightArrowUnderscoreTrueFalseTextNumberNameColorIfElifElseForToByEachInWhileDoBreakWalkAllGlobalLocalThisFunc"

var _Type_index = [...]uint16{0, 4, 8, 13, 18, 23, 30, 38, 47, 57, 67, 73, 82, 90, 103, 112, 128, 138, 151, 163, 178, 187, 197, 207, 218, 227, 237, 243, 246, 251, 259, 262, 267, 278, 288, 298, 302, 307, 311, 317, 321, 326, 328, 332, 336, 339, 341, 343, 347, 349, 354, 356, 361, 368, 374, 379, 383, 387}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
