// Code generated by "stringer -type=Type"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Dash-1]
	_ = x[Times-2]
	_ = x[Slash-3]
	_ = x[Power-4]
	_ = x[LogicOr-5]
	_ = x[LogicAnd-6]
	_ = x[BitwiseOr-7]
	_ = x[BitwiseAnd-8]
	_ = x[BitwiseXor-9]
	_ = x[Equals-10]
	_ = x[NotEquals-11]
	_ = x[LessThan-12]
	_ = x[LessThanEqual-13]
	_ = x[GreatThan-14]
	_ = x[GreaterThanEqual-15]
	_ = x[TextEquals-16]
	_ = x[TextNotEquals-17]
	_ = x[TextLessThan-18]
	_ = x[TextGreaterThan-19]
	_ = x[OpenCurve-20]
	_ = x[CloseCurve-21]
	_ = x[OpenSquare-22]
	_ = x[CloseSquare-23]
	_ = x[OpenCurly-24]
	_ = x[CloseCurly-25]
	_ = x[Assign-26]
	_ = x[Dot-27]
	_ = x[Comma-28]
	_ = x[Question-29]
	_ = x[Not-30]
	_ = x[Colon-31]
	_ = x[DoubleColon-32]
	_ = x[RightArrow-33]
	_ = x[Underscore-34]
	_ = x[At-35]
	_ = x[True-36]
	_ = x[False-37]
	_ = x[Text-38]
	_ = x[Number-39]
	_ = x[Name-40]
	_ = x[Color-41]
	_ = x[If-42]
	_ = x[Elif-43]
	_ = x[Else-44]
	_ = x[For-45]
	_ = x[To-46]
	_ = x[By-47]
	_ = x[Each-48]
	_ = x[In-49]
	_ = x[While-50]
	_ = x[Do-51]
	_ = x[Break-52]
	_ = x[WalkAll-53]
	_ = x[Global-54]
	_ = x[Local-55]
	_ = x[This-56]
	_ = x[Func-57]
	_ = x[When-58]
	_ = x[Any-59]
	_ = x[Undefined-60]
}

const _Type_name = "PlusDashTimesSlashPowerLogicOrLogicAndBitwiseOrBitwiseAndBitwiseXorEqualsNotEqualsLessThanLessThanEqualGreatThanGreaterThanEqualTextEqualsTextNotEqualsTextLessThanTextGreaterThanOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyAssignDotCommaQuestionNotColonDoubleColonRightArrowUnderscoreAtTrueFalseTextNumberNameColorIfElifElseForToByEachInWhileDoBreakWalkAllGlobalLocalThisFuncWhenAnyUndefined"

var _Type_index = [...]uint16{0, 4, 8, 13, 18, 23, 30, 38, 47, 57, 67, 73, 82, 90, 103, 112, 128, 138, 151, 163, 178, 187, 197, 207, 218, 227, 237, 243, 246, 251, 259, 262, 267, 278, 288, 298, 300, 304, 309, 313, 319, 323, 328, 330, 334, 338, 341, 343, 345, 349, 351, 356, 358, 363, 370, 376, 381, 385, 389, 393, 396, 405}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
