// Code generated by "stringer -type=Type"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Operator-0]
	_ = x[OpenCurve-1]
	_ = x[CloseCurve-2]
	_ = x[OpenSquare-3]
	_ = x[CloseSquare-4]
	_ = x[OpenCurly-5]
	_ = x[CloseCurly-6]
	_ = x[Equals-7]
	_ = x[Dot-8]
	_ = x[Comma-9]
	_ = x[Question-10]
	_ = x[Hyphen-11]
	_ = x[LesserThan-12]
	_ = x[LesserThanEquals-13]
	_ = x[GreaterThan-14]
	_ = x[GreaterThanEquals-15]
	_ = x[RightArrow-16]
	_ = x[Number-17]
	_ = x[Text-18]
	_ = x[Bool-19]
	_ = x[Alpha-20]
}

const _Type_name = "OperatorOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyEqualsDotCommaQuestionHyphenLesserThanLesserThanEqualsGreaterThanGreaterThanEqualsRightArrowNumberTextBoolAlpha"

var _Type_index = [...]uint8{0, 8, 17, 27, 37, 48, 57, 67, 73, 76, 81, 89, 95, 105, 121, 132, 149, 159, 165, 169, 173, 178}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
