// Code generated by "stringer -type=Type"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Operator-0]
	_ = x[OpenCurve-1]
	_ = x[CloseCurve-2]
	_ = x[OpenSquare-3]
	_ = x[CloseSquare-4]
	_ = x[OpenCurly-5]
	_ = x[CloseCurly-6]
	_ = x[Equals-7]
	_ = x[Dot-8]
	_ = x[Comma-9]
	_ = x[Hyphen-10]
	_ = x[LesserThan-11]
	_ = x[LesserThanEquals-12]
	_ = x[GreaterThan-13]
	_ = x[GreaterThanEquals-14]
	_ = x[RightArrow-15]
	_ = x[Number-16]
	_ = x[Text-17]
	_ = x[Bool-18]
	_ = x[Alpha-19]
}

const _Type_name = "OperatorOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyEqualsDotCommaHyphenLesserThanLesserThanEqualsGreaterThanGreaterThanEqualsRightArrowNumberTextBoolAlpha"

var _Type_index = [...]uint8{0, 8, 17, 27, 37, 48, 57, 67, 73, 76, 81, 87, 97, 113, 124, 141, 151, 157, 161, 165, 170}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
