// Code generated by "stringer -type=Type"; DO NOT EDIT.

package lex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plus-0]
	_ = x[Dash-1]
	_ = x[Times-2]
	_ = x[Slash-3]
	_ = x[Power-4]
	_ = x[Remainder-5]
	_ = x[LogicOr-6]
	_ = x[LogicAnd-7]
	_ = x[BitwiseOr-8]
	_ = x[BitwiseAnd-9]
	_ = x[BitwiseXor-10]
	_ = x[Equals-11]
	_ = x[NotEquals-12]
	_ = x[LessThan-13]
	_ = x[LessThanEqual-14]
	_ = x[GreatThan-15]
	_ = x[GreaterThanEqual-16]
	_ = x[TextEquals-17]
	_ = x[TextNotEquals-18]
	_ = x[TextLessThan-19]
	_ = x[TextGreaterThan-20]
	_ = x[OpenCurve-21]
	_ = x[CloseCurve-22]
	_ = x[OpenSquare-23]
	_ = x[CloseSquare-24]
	_ = x[OpenCurly-25]
	_ = x[CloseCurly-26]
	_ = x[Assign-27]
	_ = x[Dot-28]
	_ = x[Comma-29]
	_ = x[Question-30]
	_ = x[Not-31]
	_ = x[Colon-32]
	_ = x[DoubleColon-33]
	_ = x[RightArrow-34]
	_ = x[Underscore-35]
	_ = x[At-36]
	_ = x[True-37]
	_ = x[False-38]
	_ = x[Text-39]
	_ = x[Number-40]
	_ = x[Name-41]
	_ = x[ColorCode-42]
	_ = x[If-43]
	_ = x[Else-44]
	_ = x[For-45]
	_ = x[To-46]
	_ = x[By-47]
	_ = x[In-48]
	_ = x[While-49]
	_ = x[Do-50]
	_ = x[Break-51]
	_ = x[WalkAll-52]
	_ = x[Global-53]
	_ = x[Local-54]
	_ = x[Compute-55]
	_ = x[This-56]
	_ = x[Func-57]
	_ = x[When-58]
	_ = x[Any-59]
	_ = x[Undefined-60]
}

const _Type_name = "PlusDashTimesSlashPowerRemainderLogicOrLogicAndBitwiseOrBitwiseAndBitwiseXorEqualsNotEqualsLessThanLessThanEqualGreatThanGreaterThanEqualTextEqualsTextNotEqualsTextLessThanTextGreaterThanOpenCurveCloseCurveOpenSquareCloseSquareOpenCurlyCloseCurlyAssignDotCommaQuestionNotColonDoubleColonRightArrowUnderscoreAtTrueFalseTextNumberNameColorCodeIfElseForToByInWhileDoBreakWalkAllGlobalLocalComputeThisFuncWhenAnyUndefined"

var _Type_index = [...]uint16{0, 4, 8, 13, 18, 23, 32, 39, 47, 56, 66, 76, 82, 91, 99, 112, 121, 137, 147, 160, 172, 187, 196, 206, 216, 227, 236, 246, 252, 255, 260, 268, 271, 276, 287, 297, 307, 309, 313, 318, 322, 328, 332, 341, 343, 347, 350, 352, 354, 356, 361, 363, 368, 375, 381, 386, 393, 397, 401, 405, 408, 417}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
